# Generated by Django 4.2.2 on 2023-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_available_alter_product_quantity_in_stock_and_more'),
        ('carts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_cart',
            field=models.ManyToManyField(blank=True, related_name='cart_products', through='carts.CartItem', to='products.product'),
        ),
    ]
