# Generated by Django 4.2.2 on 2023-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
