# Generated by Django 4.2.2 on 2023-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
